### ISSUE TITLE
Fix: Agregado automático de badge de coverage

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#93]
Hoy está fallando el build de CI cuando se aprueba un PR porque la acción 

```yml
    - name: Coverage badge
      uses: demyanets/angular-coverage-badges-action@v1
      with:
        coverage-summary-path: coverage/coverage-summary.json
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

levanta y graba directamente el directorio badge a master que tiene protección de escritura directa. Lo que podemos hacer es que este proceso corra solo cuando se cree un PR, de manera que al aprobarlo se actualice el badge (sin ejecutar el proceso).
